[package]
name = "cmeet-cfrm-backend"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cmsg = { git = "https://github.com/corbet-libs/cmsg.git", rev = "7855f4b2561d28bd33d18a979b4d4ddea9a3aa19", default-features = false }
cfrm = { git = "https://github.com/corbet-libs/cfrm.git", rev = "0b30bad617dae921a77fe1a00799ee028f405443", default-features = false, features = ["discovery-valkey", "sqlite", "turso", "permit-issuer"] }
data-encoding = "2.9"
ed25519-dalek = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
