use clap::{Parser, Subcommand, ValueEnum};
use cmeet::{Format, write_json};
use cmsg::door::surface;
use std::{io, process::ExitCode};

#[derive(Parser)]
#[command(
    version,
    about = "cmeet member client",
    after_help = "Runtime actions, TUI and MCP serving await an authorized cmsg runtime. API inspection does not establish product readiness."
)]
struct Arguments {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Inspect schemas generated by the cmsg action registry; no runtime calls.
    Api {
        #[arg(value_enum, default_value = "cli")]
        projection: Projection,
        #[arg(long)]
        pretty: bool,
    },
}

#[derive(Clone, Copy, ValueEnum)]
enum Projection {
    Cli,
    Mcp,
    Openapi,
    Bundle,
}

fn main() -> ExitCode {
    let Command::Api { projection, pretty } = Arguments::parse().command;
    let value = match projection {
        Projection::Cli => surface::cli_commands(),
        Projection::Mcp => surface::mcp_tools(),
        Projection::Openapi => surface::openapi(),
        Projection::Bundle => surface::bundle(),
    };
    let format = if pretty { Format::Pretty } else { Format::Json };
    match write_json(&mut io::stdout().lock(), &value, format) {
        Ok(()) => ExitCode::SUCCESS,
        Err(_) => {
            eprintln!("cmeet: output unavailable");
            ExitCode::FAILURE
        }
    }
}
