// English strings for the forum discovery view.
// Views use these labels so future translations copy this file only.

export const forumStrings = {
  title: 'Discover',
  lead: 'Filters work both ways on real values. Public-card views stay private.',
  filters: 'Filters',
  refresh: 'Refresh',
  searching: 'Searching…',
  loading: 'Loading…',
  loadingMore: 'Loading more…',
  loadMore: 'Load more',
  empty: 'No one is around right now.',
  emptyHint: 'Members appear while they are online.',
  numberFrom: '(from)',
  numberTo: '(to)',
  yes: 'Yes',
  no: 'No',
  choose: 'Choose…',
  distanceWithinKm: '(within km)',
  wantToKnowMore: 'Want to know more',
  checkingKey: 'Checking…',
  keyAccepted: 'Key accepted. You shared your key first, so they can look back at you.',
  keyRejectedPrefix: 'Not a match on:',
  keyRejectedSuffix: 'Your matching rules stay private.',
  keyFailed: 'The key request did not work.',
  discoveryFailed: 'Discovery is unavailable right now.',
  exchangesTitle: 'Private profile exchanges',
  exchangesHint: 'Requesting a key notifies both members. Viewing a public card never does.',
  incomingLabel: 'Incoming',
  outgoingLabel: 'Outgoing',
  acceptedLabel: 'Accepted',
  rejectedLabel: 'Rejected',
  failingFieldLabel: 'Field',
  reasonLabel: 'Reason',
  lookBackNote: 'You shared your key first, so this peer can look back at you.',
  lookBackIncomingNote: 'They shared their key first, so you can look back at them.',
  previewFront: 'Front: public profile',
  previewBack: 'Back: private profile',
  writeWave: 'Write first wave',
  waveLabel: 'First wave message',
  waveSend: 'Send wave',
  waveSending: 'Sending…',
  waveEmpty: 'Write a message first.',
  waveSentPrefix: 'Wave sent. Status:',
  waveFailed: 'The wave did not send.',
} as const;

export type ForumStrings = typeof forumStrings;
