// English strings for the group detail view.
// Views use these labels so future translations copy this file only.

export const groupDetailStrings = {
  backToGroups: 'Back to groups',
  loading: 'Loading…',
  unavailable: 'This group is not available.',
  loadFailed: 'This group is unavailable.',
  hiddenNote: 'This group is hidden until you join; each mover chooses.',
  quietNote: 'Quiet here so far.',
  membersSuffix: 'members',
  whatChangesNext: 'What changes next',
  newcomerHistoryLabel: 'Newcomer history',
  bandLabel: 'Size band',
  lineageLabel: 'Lineage',
  roomConsentNote:
    "Joining means consenting to members seeing each other's private profiles. Look-back and blocking still work.",
  directContactNote:
    'To talk to someone one-to-one for the first time, send a wave. Joining, forking, merging and splitting never cost a wave.',
  directContactLink: 'Go to first contact',
  messagesLabel: 'Group messages',
  composerLabel: 'Write a group message',
  send: 'Send',
  sendBusy: 'Sending…',
  sendFailed: 'The message did not go out.',
  emptyMessage: 'Write a message first.',
  suggestionDismiss: 'Dismiss suggestion',
  dismissBusy: 'Dismissing…',
  dismissFailed: 'Dismissing did not work.',
  welcomeAction: 'Welcome a newcomer',
  welcomeBusy: 'Requesting…',
  welcomeFailed: 'The welcome request did not work.',
  welcomeReplyLabel: 'Group reply',
  forksTitle: 'Consent forks',
  forksLead:
    'Each fork is a proposal. Nobody moves by proposing. Every mover consents separately; nonmovers keep the original group.',
  noForks: 'No fork proposals yet.',
  proposedRosterLabel: 'Proposed roster',
  emptyRoster: 'No members listed yet.',
  consentAction: 'Consent to this fork',
  consentBusy: 'Recording…',
  consentedLabel: 'Consented',
  consentFailed: 'Recording consent did not work.',
  consentRecorded:
    'Consent recorded. Nonmovers keep the original group; nobody was moved automatically.',
  proposeTitle: 'Propose a fork',
  proposeLead: 'Describe the fork first. Proposing only records the proposal.',
  kindLabel: 'Fork kind',
  kinds: {
    add: 'Add members',
    exclusion: 'Exclusion fork',
    split: 'Split',
    merge: 'Merge',
    open: 'Open toward public',
    exit: 'Exit fork',
  },
  nameLabel: 'Fork name',
  namePlaceholder: 'A short name for the fork',
  detailLabel: 'What this fork is about',
  detailPlaceholder: 'One or two sentences for the other members',
  rosterLabel: 'Proposed roster (member ids, comma separated)',
  rosterPlaceholder: 'member-ana, member-tom',
  rosterHint: 'Shown exactly as typed so everyone can check it before consenting.',
  rosterPreviewLabel: 'Roster preview',
  targetLabel: 'Target group id (merge only, optional)',
  targetPlaceholder: 'group-choir',
  proposeAction: 'Propose fork',
  proposeBusy: 'Proposing…',
  proposeFailed: 'The fork proposal did not work.',
  emptyProposal: 'Describe the fork first.',
  proposalRecorded:
    'Proposal recorded. Nobody has moved. Each mover still chooses whether to consent.',
  nonmoversNote: 'Nonmovers keep the original group.',
  seatLabel: 'Seat budget',
  openingProgressLabel: 'Opening progress',
} as const;

export type GroupDetailStrings = typeof groupDetailStrings;
